### ISSUE TITLE
Flawless-18: Create basic sequence concept.

### ISSUE THREAD

**Issue by JoshuaLight** [JoshuaLight/Flawless#26]
There must be something similar to `Enumerator` or `Iterator` but in more object-oriented way. Something called `Cursor` or maybe `ForwardCursor` or even `Pointer` (at least without `Point()` method).

The basic idea is to *point* to somewhere and have a possibility to *move* in some direction.

Like:
```c#
public interface Cursor<T>
{
    T Location();
    bool Next();
}
```

Also there must be some `Sequence` interface:
```c#
public interface Sequence<T>
{
    Cursor<T> Cursor();
}
```

Right now I can't decide, but I will update that topic soon...

_P.S. Why the hell I'm talking to myself??? >.<_

**Comment by JoshuaLight** [comment]
Here is some example for inspiration:
```c#
var a = new LimitedSequence<int>(
    new List<int> { 1, 2, 3 }.AsSequence(),
    count: 1
);

Console.WriteLine( a.Count() ); // 1.
```

But the main problem is how to design proper moving along the sequence?
The idea of:
```c#
var cursor = sequence.Cursor();
while ( cursor.Next() )
{
    Console.WriteLine( cursor.Current() );
}
```
is very similar to `IEnumerable` and `IEnumerator`, at least better naming, but without native `foreach` support is excess and useless.

Let's start from scratch. What is behind `Sequence`? The idea, as for me, is similar to mathematical induction: I have some *first element* and I have a *rule*, from which I can derive other elements.
For example:
- `ArraySequence` has *first element* as `array[ 0 ]` or just some chunk of memory and the *rule*, that every next element is `array[ i + 1 ]`, where `i` is `number of element - 1`.
- `InfiniteSequence` has some *first element*, for example, number `1` and the *rule*: every `next` element is `previous * 2`. Profit!

What is the basic idea behind `Cursor` or whatever? I think it is the possibility to move along the `Sequence`, but why can't we just design it in the `Sequence` itself? The main reason, maybe, the possibility to *start from scratch*.

So now we have two basic *concepts*:
- Some concept of `Sequence`, that can be represented as `start element` and `accumulation rule`. It is important to note, that `Sequence` is always *idea* of something, not the real something, because, for example, sequence of natural numbers is actually *infinite*. So we can say just: "_Hey, this is `natural numbers sequence` object_" in the sense of *abstract* endless thing.
- Some concept of `Walk` or `Iteration` along the `Sequence`, that can be started. You can think of it as *representation* of `Sequence` in some kind of *real* world.

**Comment by gud018days** [comment]
Hi @JoshuaLight,

I'm sorry that I break into your ~dialogue~ monologue with yourself. Maybe you aren't happy to see uninvited guest.

I do not understand why you try to develop `Sequence` concept if there is `IEnumerable` already, but, well, it doesn't matter. I just think that you may consider my following input as useful so that is the reason why I am writing here.

You said that the `Sequence` was useless if there was no native support by `foreach`.
> is very similar to IEnumerable and IEnumerator, at least better naming, but without native foreach support is excess and useless.

So I just want to remind that we have an ability to create implicit (or explicit) _operator_ to cast the `Sequence` to `IEnumerable`. Thus, I suppose, your `Sequence` will be supported by `foreach` behind the scene.
